// apps/docs/snippets/preact/connection-key.tsx
declare function useAuth(): {
  userId: string;
  loginCount: number;
  getToken: () => Promise<string>;
};
// ---cut---
import type { ComponentChildren } from "preact";
import { SignalRProvider } from "./client";

export function Providers({ children }: { children: ComponentChildren }) {
  const { userId, loginCount, getToken } = useAuth();

  return (
    <SignalRProvider
      baseUrl="https://api.example.com"
      accessTokenFactory={getToken}
      connectionKey={`${userId}:${loginCount}`}
    >
      {children}
    </SignalRProvider>
  );
}

// apps/docs/snippets/solid/connection-key.tsx
import type { Component } from "solid-js";
import { render } from "solid-js/web";

declare const App: Component;
declare const userId: () => string;
declare const loginCount: () => number;
declare const getToken: () => Promise<string>;
// ---cut---
import { SignalRProvider } from "./client";

render(
  () => (
    <SignalRProvider
      baseUrl="https://api.example.com"
      accessTokenFactory={getToken}
      connectionKey={`${userId()}:${loginCount()}`}
    >
      <App />
    </SignalRProvider>
  ),
  document.getElementById("root")!,
);
