// apps/docs/snippets/react/event.tsx
import { useState } from "react";
import type { ChatMessage } from "./contract";
import { useSignalREffect } from "./client";

export function Messages({ roomId }: { roomId: string }) {
  const [messages, setMessages] = useState<ChatMessage[]>([]);

  useSignalREffect("/hubs/rooms", "MessageReceived", (message) => {
    if (message.roomId === roomId) setMessages((all) => [...all, message]);
  });

  return (
    <ul>
      {messages.map((m, index) => (
        <li key={index}>{m.user}: {m.text}</li>
      ))}
    </ul>
  );
}

// apps/docs/snippets/solid/event.tsx
import { createSignal, For } from "solid-js";
import type { ChatMessage } from "./contract";
import { useSignalREffect } from "./client";

export function Messages(props: { roomId: string }) {
  const [messages, setMessages] = createSignal<ChatMessage[]>([]);

  useSignalREffect("/hubs/rooms", "MessageReceived", (message) => {
    if (message.roomId === props.roomId) setMessages((all) => [...all, message]);
  });

  return (
    <ul>
      <For each={messages()}>{(m) => <li>{m.user}: {m.text}</li>}</For>
    </ul>
  );
}
