// apps/docs/snippets/react/protocol-switch.tsx
import { useState } from "react";
import type { ReactNode } from "react";
import { createSignalRClient } from "@dammers/use-signalr-react";
import { JsonHubProtocol } from "@microsoft/signalr";
import { MessagePackHubProtocol } from "@microsoft/signalr-protocol-msgpack";
import { hubs } from "./contract";

declare function getToken(): Promise<string>;

let useBinary = true;

const { SignalRProvider } = createSignalRClient({
  hubs,
  hubProtocol: () => (useBinary ? new MessagePackHubProtocol() : new JsonHubProtocol()),
});

export function Providers({ children }: { children: ReactNode }) {
  const [rebuilds, setRebuilds] = useState(0);

  function switchProtocol(binary: boolean) {
    useBinary = binary;
    setRebuilds((count) => count + 1);
  }

  return (
    <SignalRProvider baseUrl="https://api.example.com" accessTokenFactory={getToken} connectionKey={String(rebuilds)}>
      <button onClick={() => switchProtocol(!useBinary)}>Switch protocol</button>
      {children}
    </SignalRProvider>
  );
}

// apps/docs/snippets/solid/protocol-switch.tsx
import { createSignal } from "solid-js";
import type { Component } from "solid-js";
import { render } from "solid-js/web";
import { createSignalRClient } from "@dammers/use-signalr-solid";
import { JsonHubProtocol } from "@microsoft/signalr";
import { MessagePackHubProtocol } from "@microsoft/signalr-protocol-msgpack";
import { hubs } from "./contract";

declare const App: Component;
declare const getToken: () => Promise<string>;

const [useBinary, setUseBinary] = createSignal(true);

const { SignalRProvider } = createSignalRClient({
  hubs,
  hubProtocol: () => (useBinary() ? new MessagePackHubProtocol() : new JsonHubProtocol()),
});

render(
  () => (
    <SignalRProvider baseUrl="https://api.example.com" accessTokenFactory={getToken} connectionKey={String(useBinary())}>
      <button onClick={() => setUseBinary(!useBinary())}>Switch protocol</button>
      <App />
    </SignalRProvider>
  ),
  document.getElementById("root")!,
);
