// apps/docs/snippets/react/event.tsx
import { useState } from "react";
import type { ChatMessage } from "./contract";
import { useSignalREffect } from "./client";

export function Messages({ roomId }: { roomId: string }) {
  const [messages, setMessages] = useState<ChatMessage[]>([]);

  useSignalREffect("/hubs/rooms", "MessageReceived", (message) => {
    if (message.roomId === roomId) setMessages((all) => [...all, message]);
  });

  return (
    <ul>
      {messages.map((m, index) => (
        <li key={index}>{m.user}: {m.text}</li>
      ))}
    </ul>
  );
}

// apps/docs/snippets/vue/event.vue
<script setup lang="ts">
import { ref } from "vue";
import { useSignalREvent } from "./client";
import type { ChatMessage } from "./contract";

const props = defineProps<{ roomId: string }>();
const messages = ref<ChatMessage[]>([]);

useSignalREvent("/hubs/rooms", "MessageReceived", (message) => {
  if (message.roomId === props.roomId) messages.value.push(message);
});
</script>

<template>
  <ul>
    <li v-for="(message, index) in messages" :key="index">{{ message.user }}: {{ message.text }}</li>
  </ul>
</template>
