// apps/docs/snippets/svelte/invoke.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { hubInvoke } from "./client";
  import type { ChatMessage } from "./contract";

  let { roomId }: { roomId: string } = $props();
  let history = $state<ChatMessage[]>([]);
  let error = $state<string>();
  const getHistory = hubInvoke("/hubs/rooms", "GetHistory");

  async function load() {
    try {
      history = await getHistory(roomId);
    } catch (e) {
      if (e instanceof DOMException && e.name === "AbortError") return;
      error = e instanceof Error ? e.message : String(e);
    }
  }

  onMount(load);
</script>

{#if error}
  <p role="alert">{error}</p>
{:else}
  <ul>
    {#each history as message}
      <li>{message.text}</li>
    {/each}
  </ul>
{/if}

// apps/docs/snippets/vue/invoke.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import { useSignalRInvoke } from "./client";
import type { ChatMessage } from "./contract";

const props = defineProps<{ roomId: string }>();
const history = ref<ChatMessage[]>([]);
const error = ref<string>();
const getHistory = useSignalRInvoke("/hubs/rooms", "GetHistory");

async function load() {
  try {
    history.value = await getHistory(props.roomId);
  } catch (e) {
    if (e instanceof DOMException && e.name === "AbortError") return;
    error.value = e instanceof Error ? e.message : String(e);
  }
}

onMounted(load);
</script>

<template>
  <p v-if="error" role="alert">{{ error }}</p>
  <ul v-else>
    <li v-for="(message, index) in history" :key="index">{{ message.text }}</li>
  </ul>
</template>
