// packages/solid/src/status-store.ts
import { createSignal } from "solid-js";
import type { Accessor, Setter } from "solid-js";
import type { HubConnectionStatus, StatusStore } from "@dammers/use-signalr-core";

export type { StatusStore };

/**
 * Small store for hub statuses, backed by one Solid signal per hub, created
 * lazily on first access. Exposes only `get` and `set` — no whole-record
 * snapshot — so a per-hub read lets an effect track only the hub it reads.
 */
export function createStatusStore<H extends string>(): StatusStore<H> {
  const signals = new Map<
    H,
    [Accessor<HubConnectionStatus>, Setter<HubConnectionStatus>]
  >();

  const getOrCreate = (hub: H) => {
    let entry = signals.get(hub);
    if (!entry) {
      entry = createSignal<HubConnectionStatus>("idle");
      signals.set(hub, entry);
    }
    return entry;
  };

  return {
    get: (hub) => getOrCreate(hub)[0](),
    set: (hub, status) => getOrCreate(hub)[1](status),
  };
}

// packages/angular/src/status-store.ts
import { signal } from "@angular/core";
import type { WritableSignal } from "@angular/core";
import type { HubConnectionStatus, StatusStore as StatusStoreBase } from "@dammers/use-signalr-core";

export interface StatusStore<H extends string> extends StatusStoreBase<H> {
  /** The underlying per-hub signal; read it directly for a `computed()`/template binding. */
  signal: (hub: H) => WritableSignal<HubConnectionStatus>;
}

/**
 * Small store for hub statuses, backed by one Angular `signal()` per hub,
 * created lazily on first access. Signals need no injector (they can be
 * constructed in a plain class), and a `get`/`computed` on hub A's signal
 * never recomputes when hub B's signal is written — the selective
 * invalidation the adapter contract requires.
 */
export function createStatusStore<H extends string>(): StatusStore<H> {
  const signals = new Map<H, WritableSignal<HubConnectionStatus>>();

  const getOrCreate = (hub: H) => {
    let s = signals.get(hub);
    if (!s) {
      s = signal<HubConnectionStatus>("disconnected");
      signals.set(hub, s);
    }
    return s;
  };

  return {
    get: (hub) => getOrCreate(hub)(),
    set: (hub, status) => {
      const s = getOrCreate(hub);
      if (s() === status) return;
      s.set(status);
    },
    signal: (hub) => getOrCreate(hub),
  };
}
