// apps/docs/snippets/react/groups.tsx
import { useEffect } from "react";
import { useHubStatus, useSignalRInvoke, useSignalRTeardown } from "./client";
import { ignoreAbort } from "./ignore-abort";

export function RoomMembership({ roomId }: { roomId: string }) {
  const status = useHubStatus("/hubs/rooms");
  const joinRoom = useSignalRInvoke("/hubs/rooms", "JoinRoom");
  const leaveRoom = useSignalRTeardown("/hubs/rooms", "LeaveRoom");

  useEffect(() => {
    if (status !== "connected") return;
    joinRoom(roomId).catch(ignoreAbort);
  }, [status, roomId, joinRoom]);

  useEffect(() => {
    return () => {
      void leaveRoom(roomId);
    };
  }, [roomId, leaveRoom]);

  return null;
}

// apps/docs/snippets/svelte/groups.svelte
<script lang="ts">
  import { hubInvoke, hubStatus, hubTeardown } from "./client";
  import { ignoreAbort } from "./ignore-abort";

  let { roomId }: { roomId: string } = $props();
  const status = hubStatus("/hubs/rooms");
  const joinRoom = hubInvoke("/hubs/rooms", "JoinRoom");
  const leaveRoom = hubTeardown("/hubs/rooms", "LeaveRoom");

  $effect(() => {
    if ($status === "connected") joinRoom(roomId).catch(ignoreAbort);
  });

  $effect(() => {
    const id = roomId;
    return () => void leaveRoom(id);
  });
</script>
