// apps/docs/snippets/vue/send.vue
<script setup lang="ts">
import { ref } from "vue";
import { useSignalRSend } from "./client";

const props = defineProps<{ roomId: string }>();
const text = ref("");
const dropped = ref(false);
const send = useSignalRSend("/hubs/rooms", "SendMessage");

async function submit() {
  const sent = await send(props.roomId, text.value);
  dropped.value = !sent;
  if (sent) text.value = "";
}
</script>

<template>
  <form @submit.prevent="submit">
    <input v-model="text" />
    <button>Send</button>
    <span v-if="dropped" role="alert">Not connected. The message was dropped.</span>
  </form>
</template>

// apps/docs/snippets/svelte/send.svelte
<script lang="ts">
  import { hubSend } from "./client";

  let { roomId }: { roomId: string } = $props();
  let text = $state("");
  let dropped = $state(false);
  const send = hubSend("/hubs/rooms", "SendMessage");

  async function submit(event: SubmitEvent) {
    event.preventDefault();
    const sent = await send(roomId, text);
    dropped = !sent;
    if (sent) text = "";
  }
</script>

<form onsubmit={submit}>
  <input bind:value={text} />
  <button>Send</button>
  {#if dropped}
    <span role="alert">Not connected. The message was dropped.</span>
  {/if}
</form>
