// apps/docs/snippets/solid/provider.tsx
import type { Component } from "solid-js";
import { render } from "solid-js/web";

declare const App: Component;
declare const isSignedIn: () => boolean;
declare const getToken: () => Promise<string>;
// ---cut---
import { SignalRProvider } from "./client";

render(
  () => (
    <SignalRProvider
      baseUrl="https://api.example.com"
      accessTokenFactory={getToken}
      enabled={isSignedIn()}
    >
      <App />
    </SignalRProvider>
  ),
  document.getElementById("root")!,
);

// apps/docs/snippets/react/provider.tsx
declare function useAuth(): { isSignedIn: boolean; getToken: () => Promise<string> };
// ---cut---
"use client";

import type { ReactNode } from "react";
import { SignalRProvider } from "./client";

export function Providers({ children }: { children: ReactNode }) {
  const { isSignedIn, getToken } = useAuth();

  return (
    <SignalRProvider
      baseUrl="https://api.example.com"
      accessTokenFactory={getToken}
      enabled={isSignedIn}
    >
      {children}
    </SignalRProvider>
  );
}
