// apps/docs/snippets/angular/teardown.ts
import { Component, DestroyRef, inject } from "@angular/core";
import { injectHubTeardown } from "./client";

@Component({ selector: "app-room-session", template: "" })
export class RoomSessionComponent {
  private roomId = "general";
  private leaveRoom = injectHubTeardown("/hubs/rooms", "LeaveRoom");

  constructor() {
    inject(DestroyRef).onDestroy(() => {
      void this.leaveRoom(this.roomId);
    });
  }
}

// apps/docs/snippets/react/teardown.tsx
import { useEffect } from "react";
import { useSignalRTeardown } from "./client";

export function LeaveOnUnmount({ roomId }: { roomId: string }) {
  const leaveRoom = useSignalRTeardown("/hubs/rooms", "LeaveRoom");

  useEffect(() => {
    return () => {
      void leaveRoom(roomId);
    };
  }, [roomId, leaveRoom]);

  return null;
}
