// apps/docs/snippets/svelte/invoke.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { hubInvoke } from "./client";
  import type { ChatMessage } from "./contract";

  let { roomId }: { roomId: string } = $props();
  let history = $state<ChatMessage[]>([]);
  let error = $state<string>();
  const getHistory = hubInvoke("/hubs/rooms", "GetHistory");

  async function load() {
    try {
      history = await getHistory(roomId);
    } catch (e) {
      if (e instanceof DOMException && e.name === "AbortError") return;
      error = e instanceof Error ? e.message : String(e);
    }
  }

  onMount(load);
</script>

{#if error}
  <p role="alert">{error}</p>
{:else}
  <ul>
    {#each history as message}
      <li>{message.text}</li>
    {/each}
  </ul>
{/if}

// apps/docs/snippets/angular/invoke.ts
import { Component, afterNextRender, signal } from "@angular/core";
import { injectHubInvoke } from "./client";
import type { ChatMessage } from "./contract";

@Component({
  selector: "app-history",
  template: `
    @if (error()) {
      <p role="alert">{{ error() }}</p>
    }
    <p>{{ history().length }} messages</p>
  `,
})
export class HistoryComponent {
  history = signal<ChatMessage[]>([]);
  error = signal<string | null>(null);
  private getHistory = injectHubInvoke("/hubs/rooms", "GetHistory");

  constructor() {
    afterNextRender(() => void this.load("general"));
  }

  async load(roomId: string) {
    try {
      this.history.set(await this.getHistory(roomId));
    } catch (error) {
      if (error instanceof DOMException && error.name === "AbortError") return;
      this.error.set(error instanceof Error ? error.message : String(error));
    }
  }
}
