// apps/docs/snippets/svelte/connection-key.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { toStore } from "svelte/store";
  import { provideSignalR } from "./client";

  type Props = { userId: string | undefined; loginCount: number; token: string; children: Snippet };
  let { userId, loginCount, token, children }: Props = $props();

  provideSignalR({
    baseUrl: "https://api.example.com",
    accessTokenFactory: () => token,
    enabled: toStore(() => userId !== undefined),
    connectionKey: toStore(() => `${userId}:${loginCount}`),
  });
</script>

{@render children()}

// apps/docs/snippets/preact/connection-key.tsx
declare function useAuth(): {
  userId: string;
  loginCount: number;
  getToken: () => Promise<string>;
};
// ---cut---
import type { ComponentChildren } from "preact";
import { SignalRProvider } from "./client";

export function Providers({ children }: { children: ComponentChildren }) {
  const { userId, loginCount, getToken } = useAuth();

  return (
    <SignalRProvider
      baseUrl="https://api.example.com"
      accessTokenFactory={getToken}
      connectionKey={`${userId}:${loginCount}`}
    >
      {children}
    </SignalRProvider>
  );
}
