// apps/docs/snippets/svelte/provider.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { toStore } from "svelte/store";
  import { provideSignalR } from "./client";

  let { token, children }: { token: string | undefined; children: Snippet } = $props();

  provideSignalR({
    baseUrl: "https://api.example.com",
    accessTokenFactory: () => token ?? "",
    enabled: toStore(() => token !== undefined),
  });
</script>

{@render children()}

// apps/docs/snippets/preact/provider.tsx
declare function useAuth(): { isSignedIn: boolean; getToken: () => Promise<string> };
// ---cut---
import type { ComponentChildren } from "preact";
import { SignalRProvider } from "./client";

export function Providers({ children }: { children: ComponentChildren }) {
  const { isSignedIn, getToken } = useAuth();

  return (
    <SignalRProvider
      baseUrl="https://api.example.com"
      accessTokenFactory={getToken}
      enabled={isSignedIn}
    >
      {children}
    </SignalRProvider>
  );
}
